# Run config for DEP exploration on legs_abs morphology
# Use with: python src/run.py --config-name config_legs_abs run=train_run_legs_abs_dep learning.use_dep_exploration=True

motion_id: 0
im_eval: False
test: False
headless: True
num_threads: 1
fast_forward: True
num_motions: 1000
random_start: True

control_mode: "direct"

random_sample: False

proprioceptive_inputs: ["root_height", "root_tilt", "local_body_pos", "local_body_rot", "local_body_vel", "local_body_ang_vel", "muscle_len", "muscle_force", "feet_contacts"]
task_inputs: ["diff_local_body_pos", "diff_local_vel", "local_ref_body_pos"]

xml_path: "data/xml/legs_abs/myolegs_abdomen.xml"
motion_file: "data/kit_train_motion_dict.pkl"
smpl_data_dir: "data/smpl"
initial_pose_file: "data/initial_pose/legs_abs/initial_pose_train.pkl"
expert_path: ""

recording_biomechanics: False
deactivate_muscles: False

muscle_condition: none
init_fatigue: 0.1
init_fatigue_beta: 20.0
fatigue_aware: False

partial_reset: False
